version: '3'

services: 
    node:
        build: .
        hostname: node
        restart: always
        environment: 
            - MONGO_CONNECTION=mongodb://mongo:27017/server
        ports:
            - "3000:3000"
    mongo:
        image: mongo
        hostname: mongodb
        restart: always